version: "3.9"

services:
  web:
    build: .
    networks:
        - caddy
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    container_name: portfolio

networks:
    caddy:
        external: true